### ISSUE TITLE
Arduino Pins

### ISSUE THREAD

**Issue by meaganmkissel** [sansumbrella/MP3Trigger-for-Arduino#1]
What pin do you use to connect the Arduino to the MP3 trigger. I Have the Power and the Ground set up so the MP3 Trigger is being powered through the Arduino, but I don't know what pin to use.

**Comment by sansumbrella** [comment]
To enable communication, connect the RX/TX pins between the arduino and the mp3Trigger. The Arduino RX should go to the MP3 TX and vice-versa. Also be sure to run the ground from the trigger to the Arduino ground.

I didn't have any luck powering my MP3Trigger from the arduino board—I don't think I was getting enough juice out. Then again, I was trying to power 3 simultaneously.

Good luck, and have fun.

**Comment by meaganmkissel** [comment]
Thank you, that helps me a lot.

**Comment by meaganmkissel** [comment]
hmmm and I still can't get it to loop. _sigh_

**Comment by sansumbrella** [comment]
Make sure to call the update() function inside your Arduino loop(). Otherwise the MP3Trigger won't know what's going on. I might look into ways around that...
